# src/Resources/config/services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true

  # gezielt nur Klassen-Namespaces scannen
  SolidWork\ContaoExtraElementsBundle\ContentElement\:
    resource: '../../ContentElement/*'

#  SolidWork\ContaoExtraElementsBundle\Controller\:
#    resource: '../../Controller/*'

#  SolidWork\ContaoExtraElementsBundle\EventListener\:
#    resource: '../../EventListener/*'

  # Globales Exclude als Fallback (falls du später breiter lädst)
  SolidWork\ContaoExtraElementsBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity,Resources,Tests}'