services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Alle PHP-Klassen des Bundles als Services laden
  SolidWork\ContaoExtraElementsBundle\:
    resource: '../../'         # von src/Resources/config/ zwei Ebenen hoch -> src/
    exclude:
      # Contao-Ressourcen sind KEINE Services -> ausschließen
      - '../../contao'
      - '../../contao/*'
      - '../../contao/{dca,languages,templates}'
