services:
  SolidWork\ContaoExtraElementsBundle\ContentElement\TitleSubtitleElement:
    public: true
    tags:
      - { name: 'contao.content_element', category: 'texts', template: 'ce_title_subtitle', type: 'title_subtitle' }