# src/Resources/config/services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Alle PHP-Klassen des Bundles als Services laden
  SolidWork\ContaoExtraElementsBundle\:
    resource: '../../'
    # WICHTIG: Contao-Resourcen NICHT als Services registrieren
    exclude:
      - '../../contao/*'
      - '../../contao/{dca,languages,templates}'
      - '../../config/{services.yaml,packages}'