# config/services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true

  # Gezieltes Scannen einzelner Namespaces (Pfade relativ zu diesem File: config/)
  SolidWork\ContaoExtraElementsBundle\ContentElement\:
    resource: '../src/ContentElement/*'

  SolidWork\ContaoExtraElementsBundle\DependencyInjection\:
    resource: '../src/DependencyInjection/*'

#  SolidWork\ContaoExtraElementsBundle\Controller\:
#    resource: '../src/Controller/*'

#  SolidWork\ContaoExtraElementsBundle\EventListener\:
#    resource: '../src/EventListener/*'

  # Globales Exclude als Fallback (falls du später breiter lädst)
  SolidWork\ContaoExtraElementsBundle\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Resources,Tests}'

  # Stelle sicher, dass der Callback-Dienst öffentlich ist (Contao ruft ihn direkt aus dem Container auf)
  SolidWork\ContaoExtraElementsBundle\Backend\LabelCallbacks:
    public: true