# config/services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true

  # Globales Exclude als Fallback (falls du später breiter lädst)
  SolidWork\ContaoExtraElementsBundle\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Resources,Tests}'

  # Stelle sicher, dass der Callback-Dienst öffentlich ist (Contao ruft ihn direkt aus dem Container auf)
  SolidWork\ContaoExtraElementsBundle\Backend\LabelCallbacks:
    public: true
